### ISSUE TITLE
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported

### ISSUE THREAD

**Issue by AlexShavkuta** [Picovoice/react-native-voice-processor#33]
### Expected behaviour
The expected behavior is for the app to build without any errors

### Actual behaviour
Error during build on android

### Affected platforms
Android devices

### Output of `npx react-native info`
```
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 82.17 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false
```

### Steps to reproduce the behaviour
1. run an app that implements react native 0.72.10
2. The error will occur during build

(Include enough details so that the issue can be reproduced independently.)

### Stacktrace
```
FAILURE: Build failed with an exception.

* What went wrong:*
Execution failed for task ':picovoice_porcupine-react-native:processDebugManifest'.
> A failure occurred while executing com.android.build.gradle.tasks.ProcessLibraryManifest$ProcessLibWorkAction
   > Incorrect package="ai.picovoice.reactnative.porcupine" found in source AndroidManifest.xml: /Users/Github/porcuSafe/node_modules/@picovoice/porcupine-react-native/android/src/main/AndroidManifest.xml.
     Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
     Recommendation: remove package="ai.picovoice.reactnative.porcupine" from the source AndroidManifest.xml: /Users/Github/porcuSafe/node_modules/@picovoice/porcupine-react-native/android/src/main/AndroidManifest.xml.
```

**Comment by laves** [comment]
@AlexShavkuta - thanks for the report. Do you experience the same issue with the [example](https://github.com/Picovoice/react-native-voice-processor/tree/main/example)?

**Comment by AlexShavkuta** [comment]
No, I'm not experiencing the same issue in the example.

**Comment by laves** [comment]
I've taken a look and it seems that our plugin will not support projects built with Android Gradle Plugin > 8 due to some changes in Android Manifest format. We will put up for a fix this in the coming weeks. For now, if you use `gradle-7.5-bin.zip` in your `gradle-wrapper.properties` and set `classpath 'com.android.tools.build:gradle:7.4.2'` in your `build.gradle`, your project should build.

**Comment by laves** [comment]
@AlexShavkuta - we've addressed the issue in the latest releases (`react-native-voice-processor@1.2.2` and `porcupine-react-native@3.0.2`). You will still see a warning about package names, but that is just a trade-off for backwards compatibility. It should now build successfully with Gradle 8.

**Comment by AlexShavkuta** [comment]
Thank you very much for the quick fix.

**Comment by laves** [comment]
No problem!
