### ISSUE TITLE
[Question]: Does this package support to provide audio file after capturing audio?

### ISSUE THREAD

**Issue by chetanbhadarka** [Picovoice/react-native-voice-processor#38]
**Query:**

- I need to know does this package is able to provide audio file after capturing done?
- Does this package is compatible with other Picovoice Packages (i.e, Cheetah Speech-to-Text and leopard Speech-to-Text)?

**My Usage:**

- I need to create functionality where user can Speak and able to see live conversation in Text.
- When user stop then need to get audio file which recored all the speech of user from start-to-end.
- Also user have 2 buttons for Start and Stop. So need to listen/record until user press the stop button.

**Comment by laves** [comment]
@chetanbhadarka, thank you for your interest. Hope this helps:

- Since this library is for real-time audio processing, we don't support writing to an audio file as part of it. To do that all you must do is buffer the audio data as it comes in and then write it to a WAV file by either using another library or writing the WAV header yourself. 

- Yes, this library is compatible with all of Picovoice's other react-native packages. Some packages integrate it [into the SDK](https://github.com/Picovoice/porcupine/blob/master/binding/react-native/src/porcupine_manager.tsx) and some [use it in the demo](https://github.com/Picovoice/cheetah/tree/master/demo/react-native).

**Comment by chetanbhadarka** [comment]
**@laves,** thank you for suggestion and hope It'll work.

**Comment by chetanbhadarka** [comment]
> @chetanbhadarka, thank you for your interest. Hope this helps:
> 
> * Since this library is for real-time audio processing, we don't support writing to an audio file as part of it. To do that all you must do is buffer the audio data as it comes in and then write it to a WAV file by either using another library or writing the WAV header yourself.
> * Yes, this library is compatible with all of Picovoice's other react-native packages. Some packages integrate it [into the SDK](https://github.com/Picovoice/porcupine/blob/master/binding/react-native/src/porcupine_manager.tsx) and some [use it in the demo](https://github.com/Picovoice/cheetah/tree/master/demo/react-native).

Hi @laves, I've some queries regarding this package.
1. Getting Frame in frame listener (I'm not understanding what is frame and what is the purpose of it.)
2. Why it getting too many times?
3. Not able to find how can i do buffer audio data, because in your API documentation Just getting Frame.
4. Title in your doc is "Audio Recording Software" but not have features or not any guide to generate any audio file.

I Appreciate the SDK modules but at least need proper documentation with explanation and example as well.

**Comment by laves** [comment]
@chetanbhadarka - please see the [official demo](https://github.com/Picovoice/react-native-voice-processor/tree/main/example) for usage, as well as our [quick start](https://github.com/Picovoice/react-native-voice-processor/tree/main/example) and [API documentation](https://picovoice.ai/docs/api/voiceprocessor-react-native/). As I mentioned before, this package is for real-time audio capture (a.k.a. recording) and does not support capture-to-file or internal buffering. Audio recording/capture is just referring to the device's microphone recording and sending audio data to the user. We may consider file storage in the future as an additional feature, but be mindful that it is not wrong that it doesn't support it, it is just a feature that you would like that is not currently supported. We ask that if you are requesting a feature, you label it as `enhancement` and clearly describe the feature you are asking that we add. I'm going to close this issue as it doesn't have the proper focus for an actionable issue.
